//
//  ViewController.swift
//  FirebaseDemo
//
//  Created by lee bennett on 11/10/21.
//

import UIKit
import Firebase

class ViewController: UIViewController {
    @IBOutlet weak var emailTextField: UITextField!
    
    @IBOutlet weak var passwordTextField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let ref = Firebase.firestore().collection("users").document("john")
        
        // Creating / updating data
//        let usersCollection = Firestore.firestore().collection("users")
//
//        let johnReference = usersCollection.document("john")
//
////        johnReference.setData(["name": "John"], merge: true) { err in
////            if let err = err{
////                print(err.localizedDescription)
////            } else{
////                print("we wrote the content to firestore")
////            }
////        }
//
//
//        // Create data with an autogenerated push key inside the document
////        let documentId = Firestore.firestore().collection("users").document().documentID
////        Firestore.firestore().collection("users").document(documentId).setData(["id": documentId, "name": "Bob"], completion: nil)
//
////        print(documentId)
////        Firestore.firestore().collection("users").document("1").delete()
//
//        // Create data with an autogenerated push key
////        Firestore.firestore().collection("users")
////            .addDocument(data: ["name" : "Andrew", "grade": "A"], completion: nil)
//
//
//        Firestore.firestore().collection("users").document("john").getDocument { snap, err in
//            let data = snap?.data()
//            let documentId = snap?.documentID
//            print("getDocument - document id \(documentId) data \(data)")
//        }
//
//
//        Firestore.firestore().collection("users").document("john").addSnapshotListener { snap, err in
//            let data = snap?.data()
//            let documentId = snap?.documentID
//            print("addSnapshotListener - document id \(documentId) data \(data)")
//        }
        
        
    }

    
    @IBAction func createUserDidTapped(_ sender: UIButton) {
        // TODO - Validate the fields
        let email = emailTextField.text!
        let password = passwordTextField.text!
        
        Auth.auth().createUser(withEmail: email, password: password) { authResult, err in
            print(authResult?.user.uid)
        }
    }
    
}


struct Person{
    let name: String
}
